### ISSUE TITLE
bug when marking all as read

### ISSUE THREAD

**Issue by mrruz** [Ne4to/InoreaderFree#41]
When marking everything as read it returns error code 400, ( bad request).

**Comment by Ne4to** [comment]
@mrruz 
What version do you use?
Do you mark all as read for a single subscription or for a folder?
What is subscription url? (Web UI - Preferences - Subscriptions - click an item - XML Address field)

**Comment by mrruz** [comment]
marking all as read does this with all subscriptions, it's not one single subscription that is an issue.

The version is 1.1.3.15
